# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6192be01af40c75ed35b35724f306533fecf23f8a2cfaf47cdaeab5559189fa7b4538cb32d942e8fe9f447ea7fb5bcae83e58e65b8739620dab41b4425153aee

test:
  secret_key_base: 04679ea60ec055898d5de3041b1da2f44695fc63eee86d237344a7d9245eb0416234f2fe46d335758c58f6a5707416d2dbd46451ad5e34c8692a07fbada11a88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
